name: Feature Request
description: Suggest a new feature or improvement for Task Manager Pro
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the sections below to help us understand your request.
        
        **Before submitting**: Please search existing issues to see if this feature has already been requested.
        
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - UI/UX Improvement
        - New System Monitoring Feature
        - Performance Enhancement
        - New API Endpoint
        - Cross-Platform Support
        - Data Export/Import
        - Visualization/Charts
        - Process Management
        - Configuration/Settings
        - Other
    validations:
      required: true
      
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like
      placeholder: "Describe the feature you want to see"
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        e.g., "I'm always frustrated when..."
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        Describe your ideal solution:
        - How should it work?
        - What should the user interface look like?
        - How should it behave?
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions you've considered
      placeholder: "Have you considered other ways to solve this problem?"
      
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        Example use cases:
        1. When monitoring a development server...
        2. When analyzing system performance...
        3. When troubleshooting a slow application...
    validations:
      required: true
      
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Any examples from other tools or mockups
      placeholder: |
        References or inspiration:
        - Similar feature in Windows Task Manager
        - Example from htop/Activity Monitor
        - Link to mockup or screenshot
        
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical/blocking issue
    validations:
      required: true
      
  - type: dropdown
    id: effort
    attributes:
      label: Implementation Complexity (your guess)
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (few hours)
        - Medium (few days)
        - Complex (weeks)
        - Very Complex (months)
        - Not sure
        
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature myself
          required: false
        - label: I can help with testing
          required: false
        - label: I can help with documentation
          required: false
        - label: I can provide feedback during development
          required: false
          
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help
      placeholder: "Add any other context, screenshots, or examples here"
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I have provided sufficient detail for evaluation
          required: true